#!/bin/sh
yum update -y
timedatectl set-timezone America/Sao_Paulo
yum install -y httpd
yum install -y git
systemctl enable --now httpd
cd /
mkdir /mnt/nfs
git clone https://github.com/Alexandreerik/Compass.uol-PB-Atv2.git
cp Compass.uol-PB-Atv2/etc/crontab /etc/crontab
cp Compass.uol-PB-Atv2/etc/fstab /etc/fstab
mount -a
